vti_encoding:SR|utf8-nl
vti_author:SR|julwes
vti_modifiedby:SR|julwes
vti_timecreated:TR|26 Sep 2000 14:07:36 -0000
vti_timelastmodified:TR|26 Sep 2000 14:07:36 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.3406
vti_syncwith_d5023.us.sas.com\:80/temp3:TR|26 Sep 2000 14:07:36 -0000
vti_syncofs_ftp.freesqlhost.com\:21:TW|24 Oct 2000 11:00:00 -0000
vti_syncwith_ftp.freesqlhost.com\:21:TR|26 Sep 2000 14:07:36 -0000
vti_syncwith_pctts1.us.sas.com\:80/tempweb:TR|26 Sep 2000 14:07:36 -0000
